[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "llm-api-access"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "rich",
    "requests",
    "omegaconf",
]
