######### llm_args #########
llm: gpt-4o-mini
endpoint_name: openai
base_url: https://api.openai.com

######### generation_args #########
temperature: 0.0
top_p: 0.7
n: 1
max_completion_tokens: 1024

######### data_args #########
prompt_template: "{query}"
dataset_name: dataset
dataset_filepath: /path/to/dataset
output_filepath: runs/test/gpt-4o-mini/results.jsonl

######### running_args #########
num_threads: 16
generate_log_file: true
save_as_json: true
