######### llm_args #########
llm: gpt-3.5-turbo-0125
endpoint_name: openai
endpoint_url: https://api.openai.com

######### generation_args #########
temperature: 0.0
top_p: 0.7
n: 1
max_tokens: 1024

######### data_args #########
prompt_template: "{query}"
dataset_name: dataset
dataset_filepath: /path/to/dataset
output_filepath: runs/${dataset_name}/${llm}/${prompt_name}/results.jsonl

######### running_args #########
num_threads: 16
generate_log_file: true
